In [17]:
import numpy as np

In [18]:
A = np.array([[1,2],
              [3,4]])

In [19]:
print(A)

[[1 2]
 [3 4]]


In [20]:
B = np.array([[5,6],
              [7,8]])

In [21]:
A+B

array([[ 6,  8],
       [10, 12]])

In [22]:
C = A+B

In [23]:
print(C)

[[ 6  8]
 [10 12]]


In [24]:
#行列の積を求める
A @ B

array([[19, 22],
       [43, 50]])

In [29]:
A = np.array([[2,1,-3],
                [-1,2,1],
                [3,2,1]])

In [32]:
#Aの逆行列を求める
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.         -0.25        0.25      ]
 [ 0.14285714  0.39285714  0.03571429]
 [-0.28571429 -0.03571429  0.17857143]]


In [33]:
A @ A_inv

array([[1.00000000e+00, 2.08166817e-17, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.04083409e-16, 1.00000000e+00]])

In [41]:
A = np.array([[1,3,7],
              [2,1,4],
              [5,2,9]])

In [42]:
#Aの逆行列を求める
#A_inv = np.linalg.inv(A)
#print(A_inv)
np.linalg.pinv(A)

array([[-0.26068376,  0.05555556,  0.1965812 ],
       [ 0.18119658, -0.02222222, -0.09401709],
       [ 0.1017094 ,  0.01111111,  0.00854701]])

In [44]:
A @ A_inv

array([[-1.57142857,  0.67857143,  1.60714286],
       [-1.        , -0.25      ,  1.25      ],
       [-2.28571429, -0.78571429,  2.92857143]])

In [47]:
det_A = np.linalg.det(A)
print(det_A)

0.0


In [49]:
#固有ベクトル
A = [[2,4],[3,13]]
eig_A = np.linalg.eig(A)
print(eig_A)

(array([ 1., 14.]), array([[-0.9701425 , -0.31622777],
       [ 0.24253563, -0.9486833 ]]))
